### PR TITLE
SSL in CRON link (if available) and module name change.

### PR DESCRIPTION
**Pull request by ghost**
Answer to https://github.com/PrestaShop/PrestaShop/issues/18570
https://github.com/PrestaShop/PrestaShop/issues/9799

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi and  thanks for your pull request.
Can you please rebase it for the dev branch?

**Comment by Progi1984** [comment]
Hello @PrestaShark, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by andromaque** [comment]
This change is stuck since May, should we create a new PR or is it possible for an admin to rebase this PR to dev?

**Comment by PierreRambaud** [comment]
> This change is stuck since May, should we create a new PR or is it possible for an admin to rebase this PR to dev?

You can create a new pull request :wink:

**Pull request closed without merging**
